version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    commit-message:
      prefix: "deps"
    env:
      MONGODB_KEY: ${{dependabot}}
      AUTH_SECRET: ${{dependabot}}
      AUTH_GITHUB_ID: ${{dependabot}}
      AUTH_GITHUB_SECRET: ${{dependabot}}
      AUTH_GOOGLE_ID: ${{dependabot}}
      AUTH_GOOGLE_SECRET: ${{dependabot}}
      STRIPE_SECRET_KEY: ${{dependabot}}
      FREE_PLAN_ID: ${{dependabot}}
      BASIC_PLAN_ID: ${{dependabot}}
      PLUS_PLAN_ID: ${{dependabot}}
      PRO_PLAN_ID: ${{dependabot}}
      WEBMAIL_USER: ${{dependabot}}
      WEBMAIL_PASS: ${{dependabot}}
      PINATA_JWT: ${{dependabot}}
      PINATA_GATEWAY: ${{dependabot}}
