name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: 🚀 Features
    labels: [feature, enhancement]
  - title: 🐛 Fixes
    labels: [fix, bug]
  - title: 🧰 Maintenance
    labels: [chore]
change-template: "- $TITLE (#$NUMBER)"
template: |
  ## Changes
  $CHANGES